# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0678a5e3918ca8ae614507af83fb665a872b0af11367fdda1ee115c2058a26347313a37ce5bc4c6542f0dfb974ca7fb436872979b6e672018c617cdb0e7b945

test:
  secret_key_base: 28c557decf6518efb3f60112d95dc6f101b0c33d963c92ff1a9e9c3717b1e3b4798ec1f2ca3856b04ee15dff442fe57078f8c277dc0a81d727441bdf5d5f847a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
